version: "3"  

services:  
<<<<<<< HEAD
  
  # Initialize nginx server that serves static files
=======
  mongodb-seed:
    image: bwnyasse/docker-mongodb-worker
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB_NAME=resamvi
      - MONGO_COLLECTION_NAME=entries
    depends_on:
      - mongodb
    command: "/start.sh -i"
  
  mongodb:
    image: mongo:3.4-jessie
    volumes:
      - ./srv/mongodb.conf:/etc/mongodb.conf
      - ./srv/data:/data/db
    ports:
      - "27017:27017"

>>>>>>> ff88daa4361510896df9c15d30889875e2a4d545
  nginx:
    image: nginx
    volumes:
      - ./srv/nginx.conf:/etc/nginx/nginx.conf
      - ./build/:/usr/share/nginx/website
    ports:
      - "9001:9001"
<<<<<<< HEAD

  # Initialize database
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  # Put written entries into database
  mongodb-seed:
    image: bwnyasse/docker-mongodb-worker
    command: "/start.sh -i"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB_NAME=worker
      - MONGO_COLLECTION_NAME=users
    depends_on:
      - mongodb
    volumes:
      - ./srv/data:/tmp/mongodb/
=======
>>>>>>> ff88daa4361510896df9c15d30889875e2a4d545
  
  # Run go server that handles dynamic entry loading
  go:
    image: golang
    volumes:
      - ../go/:/go/
      - ./srv/server.go:/srv/server.go
    command: go run /srv/server.go
    ports:
      - "8080:8080"

    