version: "3"  

services:  
  mongodb:
    image: mongo:3.4-jessie
    volumes:
      - ./srv/mongodb.conf:/etc/mongodb.conf
      - ./srv/data:/data/db
    ports:
      - "27017:27017"

  nginx:
    image: nginx
    volumes:
      - ./srv/nginx.conf:/etc/nginx/nginx.conf
      - ./build/:/usr/share/nginx/website
    ports:
      - "9001:9001"
  
  go:
    image: golang
    volumes:
      - ./srv/server:/srv/server
      - ./wait-for-it.sh:/wait-for-it.sh
    ports:
      - "8080:8080"
    command: /srv/server

    